name: Deploy to Amazon S3

on:
  push:
    branches: [ "main" ]

env:
  BUCKET_NAME: personalsite20220927212606686600000001
  DISTRIBUTION_ID: EXLQBYH56WXX0

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Caching Gatsby
      id: gatsby-cache-build
      uses: actions/cache@v3
      with:
        path: |
          public
          .cache
          node_modules
        key: ${{ runner.os }}-personalsite-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-personalsite-
    
    - name: Install Dependencies
      run: npm install

    - name: Build Gatsby
      run: npm run build

    - name: Deploy to S3
      run: aws s3 sync ./public/ s3://${{ env.BUCKET_NAME }} --delete

    - name: Clear Cache
      run: aws cloudfront create-invalidation --distribution-id ${{ env.DISTRIBUTION_ID }} --paths '/*';"
    
